export const motleyCrueSongs = [
  // Dr. Feelgood (1989)
  {
    name: "Dr. Feelgood",
    album: "Dr. Feelgood",
    releaseYear: 1989,
    timesPlayed: 1200,
    imageUrl: "public/album_covers/Dr_feelgood.png",
    altText: "",
  },
  {
    name: "Kickstart My Heart",
    album: "Dr. Feelgood",
    releaseYear: 1989,
    timesPlayed: 1150,
    imageUrl: "public/album_covers/Dr_feelgood.png",
    altText: "",
  },
  {
    name: "Same Ol' Situation (S.O.S.)",
    album: "Dr. Feelgood",
    releaseYear: 1989,
    timesPlayed: 950,
    imageUrl: "public/album_covers/Dr_feelgood.png",
    altText: "",
  },
  {
    name: "Without You",
    album: "Dr. Feelgood",
    releaseYear: 1989,
    timesPlayed: 800,
    imageUrl: "public/album_covers/Dr_feelgood.png",
    altText: "",
  },
  {
    name: "Don't Go Away Mad (Just Go Away)",
    album: "Dr. Feelgood",
    releaseYear: 1989,
    timesPlayed: 780,
    imageUrl: "public/album_covers/Dr_feelgood.png",
    altText: "",
  },

  // Shout at the Devil (1983)
  {
    name: "Shout at the Devil",
    album: "Shout at the Devil",
    releaseYear: 1983,
    timesPlayed: 1500,
    imageUrl: "public/album_covers/Shout_devil.png",
    altText: "",
  },
  {
    name: "Looks That Kill",
    album: "Shout at the Devil",
    releaseYear: 1983,
    timesPlayed: 1400,
    imageUrl: "public/album_covers/Shout_devil.png",
    altText: "",
  },
  {
    name: "Too Young to Fall in Love",
    album: "Shout at the Devil",
    releaseYear: 1983,
    timesPlayed: 900,
    imageUrl: "public/album_covers/Shout_devil.png",
    altText: "",
  },
  {
    name: "Bastard",
    album: "Shout at the Devil",
    releaseYear: 1983,
    timesPlayed: 600,
    imageUrl: "public/album_covers/Shout_devil.png",
    altText: "",
  },
  {
    name: "Helter Skelter",
    album: "Shout at the Devil",
    releaseYear: 1983,
    timesPlayed: 500,
    imageUrl: "public/album_covers/Shout_devil.png",
    altText: "",
  },

  // The Dirt Soundtrack (2019)
  {
    name: "The Dirt (Est. 1981)",
    album: "The Dirt Soundtrack",
    releaseYear: 2019,
    timesPlayed: 400,
    imageUrl: "public/album_covers/Dirt_soundtrack.png",
    altText: "",
  },
  {
    name: "Ride with the Devil",
    album: "The Dirt Soundtrack",
    releaseYear: 2019,
    timesPlayed: 300,
    imageUrl: "public/album_covers/Dirt_soundtrack.png",
    altText: "",
  },
  {
    name: "Crash and Burn",
    album: "The Dirt Soundtrack",
    releaseYear: 2019,
    timesPlayed: 350,
    imageUrl: "public/album_covers/Dirt_soundtrack.png",
    altText: "",
  },
  {
    name: "Like a Virgin",
    album: "The Dirt Soundtrack",
    releaseYear: 2019,
    timesPlayed: 200,
    imageUrl: "public/album_covers/Dirt_soundtrack.png",
    altText: "",
  },
  {
    name: "On with the Show",
    album: "The Dirt Soundtrack",
    releaseYear: 2019,
    timesPlayed: 250,
    imageUrl: "public/album_covers/Dirt_soundtrack.png",
    altText: "",
  },

  // Too Fast for Love (1981)
  {
    name: "Live Wire",
    album: "Too Fast for Love",
    releaseYear: 1981,
    timesPlayed: 1000,
    imageUrl: "public/album_covers/Too_fast.png",
    altText: "",
  },
  {
    name: "Take Me to the Top",
    album: "Too Fast for Love",
    releaseYear: 1981,
    timesPlayed: 800,
    imageUrl: "public/album_covers/Too_fast.png",
    altText: "",
  },
  {
    name: "Piece of Your Action",
    album: "Too Fast for Love",
    releaseYear: 1981,
    timesPlayed: 750,
    imageUrl: "public/album_covers/Too_fast.png",
    altText: "",
  },
  {
    name: "Too Fast for Love",
    album: "Too Fast for Love",
    releaseYear: 1981,
    timesPlayed: 900,
    imageUrl: "public/album_covers/Too_fast.png",
    altText: "",
  },
  {
    name: "Merry-Go-Round",
    album: "Too Fast for Love",
    releaseYear: 1981,
    timesPlayed: 650,
    imageUrl: "public/album_covers/Too_fast.png",
    altText: "",
  },
];
